apiVersion: apps/v1
kind: Deployment
metadata:
  name: natrium-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: natrium-server
  template:
    metadata:
      labels:
        app: natrium-server
    spec:
      containers:
      - name: natrium-server
        image: replaceme
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 500m
            memory: 1Gi
        ports:
        - containerPort: 3000
          name: api
        env:
          - name: REDIS_HOST
            value: redis.redis
          - name: REDIS_DB
            value: "10"
          - name: RPC_URL
            value: http://10.8.0.2:7076
